const express=require('express');const router=express.Router();const Joi=require('joi');const bcrypt=require('bcryptjs');const fs=require('node:fs/promises');const path=require('node:path');const{randomUUID}=require('node:crypto');
const{pool}=require('../../config/db');const asyncHandler=require('../../utils/asyncHandler');const{resolveInventoryScope,inventoryScope}=require('../../utils/inventoryAccess');const{createCycle,startCycle,captureCount,completeCycle,cancelCycle}=require('../../services/inventoryCycleCounts');
const directory=path.resolve(process.env.INVENTORY_COUNT_EVIDENCE_DIR||path.join(__dirname,'../../../uploads/inventory-counts'));const filenamePattern=/^[0-9a-f-]{36}\.(jpg|png|webp)$/;const evidencePattern=/^\/inventario\/conteos\/evidencias\/[0-9a-f-]{36}\.(jpg|png|webp)$/;
const id=Joi.number().integer().min(1).max(Number.MAX_SAFE_INTEGER).required();const decimal=Joi.string().pattern(/^(0|[1-9]\d{0,11})(\.\d{1,6})?$/).required();
const listSchema=Joi.object({sucursal_id:id.optional(),estado:Joi.string().valid('PROGRAMADO','EN_PROCESO','COMPLETADO','CANCELADO').optional(),dias:Joi.number().integer().min(1).max(3650).default(90),limit:Joi.number().integer().min(1).max(100).default(50),offset:Joi.number().integer().min(0).max(1000000).default(0)});
function fail(message,status=400){throw Object.assign(new Error(message),{status});}function validate(schema,value){const result=schema.validate(value,{abortEarly:false,allowUnknown:false});if(result.error)fail('Revisa los campos: '+result.error.details.map(item=>item.path.join('.')).join(', '));return result.value;}
async function cycleScope(req,cycleId){const[rows]=await pool.query('SELECT sucursal_id,estado FROM inv_conteo_ciclico WHERE id=?',[cycleId]);if(!rows.length)fail('El conteo no existe.',404);await resolveInventoryScope(req.user,rows[0].sucursal_id,pool);return rows[0];}
async function verifyPassword(userId,value){const[rows]=await pool.query('SELECT password_hash FROM usuario WHERE id=? AND activo=1',[userId]);if(!rows.length||!await bcrypt.compare(value,rows[0].password_hash))fail('La contraseña es incorrecta.',403);}
function scopeFilter(user,column='i.sucursal_id'){const ids=inventoryScope(user);if(ids===null)return{sql:'1=1',params:[]};return{sql:`${column}=?`,params:[ids[0]]};}

router.get('/conteos',asyncHandler(async(req,res)=>{const q=validate(listSchema,req.query);if(q.sucursal_id)await resolveInventoryScope(req.user,q.sucursal_id,pool);const filter=q.sucursal_id?{sql:'i.sucursal_id=?',params:[q.sucursal_id]}:scopeFilter(req.user);const conditions=[filter.sql],params=[...filter.params];if(q.estado){conditions.push('i.estado=?');params.push(q.estado);}const where=conditions.join(' AND ');const[[count]]=await pool.query(`SELECT COUNT(*) total FROM inv_conteo_ciclico i WHERE ${where}`,params);const[items]=await pool.query(`SELECT i.*,s.nombre sucursal_nombre,a.nombre almacen_nombre,creator.nombre creado_por_nombre,assigned.nombre asignado_a_nombre,
    (SELECT COUNT(*) FROM inv_conteo_ciclico_detalle d WHERE d.conteo_id=i.id) partidas,(SELECT COUNT(*) FROM inv_conteo_ciclico_detalle d WHERE d.conteo_id=i.id AND d.cantidad_contada IS NOT NULL) partidas_contadas,
    (SELECT COUNT(*) FROM inv_conteo_ciclico_detalle d WHERE d.conteo_id=i.id AND d.ajuste_solicitud_id IS NOT NULL) diferencias
    FROM inv_conteo_ciclico i JOIN cat_sucursal s ON s.id=i.sucursal_id JOIN inv_almacen a ON a.id=i.almacen_id JOIN usuario creator ON creator.id=i.creado_por LEFT JOIN usuario assigned ON assigned.id=i.asignado_a
    WHERE ${where} ORDER BY i.semana DESC,i.created_at DESC LIMIT ? OFFSET ?`,[...params,q.limit,q.offset]);if(items.length){const[details]=await pool.query(`SELECT d.id,d.conteo_id,d.producto_id,d.ubicacion_id,d.estado,d.cantidad_contada,d.diferencia,d.evidencia_url,d.notas,d.contado_at,d.ajuste_solicitud_id,
      p.sku,p.nombre_comercial,u.codigo ubicacion_codigo,aj.estado ajuste_estado,d.existencia_sistema
      FROM inv_conteo_ciclico_detalle d JOIN inv_producto p ON p.id=d.producto_id JOIN inv_ubicacion u ON u.id=d.ubicacion_id LEFT JOIN inv_ajuste_solicitud aj ON aj.id=d.ajuste_solicitud_id
      WHERE d.conteo_id IN (${items.map(()=>'?').join(',')}) ORDER BY u.codigo,p.nombre_comercial`,items.map(row=>row.id));for(const item of items)item.detalles=details.filter(detail=>Number(detail.conteo_id)===Number(item.id)).map(detail=>({...detail,existencia_sistema:detail.cantidad_contada===null&&item.estado!=='COMPLETADO'?null:detail.existencia_sistema}));}res.json({items,total:Number(count.total),limit:q.limit,offset:q.offset});}));

router.post('/conteos',asyncHandler(async(req,res)=>{const body=validate(Joi.object({sucursal_id:id,almacen_id:id,semana:Joi.date().iso().required(),zona:Joi.string().trim().uppercase().pattern(/^[A-Z0-9_. -]{1,60}$/).required(),cantidad_productos:Joi.number().integer().min(1).max(100).default(10),asignado_a:id.optional()}),req.body);await resolveInventoryScope(req.user,body.sucursal_id,pool);if(body.asignado_a){const[users]=await pool.query('SELECT id FROM usuario WHERE id=? AND activo=1',[body.asignado_a]);if(!users.length)fail('El usuario asignado no existe o está inactivo.');}res.status(201).json(await createCycle(body,Number(req.user.sub)));}));
router.post('/conteos/:id/iniciar',asyncHandler(async(req,res)=>{const cycleId=validate(id,req.params.id);await cycleScope(req,cycleId);res.json(await startCycle(cycleId,Number(req.user.sub)));}));
router.put('/conteos/:id/partidas/:detailId',asyncHandler(async(req,res)=>{const cycleId=validate(id,req.params.id),detailId=validate(id,req.params.detailId);await cycleScope(req,cycleId);const body=validate(Joi.object({cantidad_contada:decimal,evidencia_url:Joi.string().pattern(evidencePattern).allow('',null).empty('').default(null),notas:Joi.string().trim().max(500).allow('',null).empty('').default(null)}),req.body);if(body.evidencia_url){const filename=body.evidencia_url.split('/').pop();try{await fs.access(path.join(directory,filename));}catch{fail('La evidencia no existe.');}}res.json(await captureCount(cycleId,detailId,body,Number(req.user.sub)));}));
router.post('/conteos/:id/completar',asyncHandler(async(req,res)=>{const cycleId=validate(id,req.params.id);await cycleScope(req,cycleId);res.json(await completeCycle(cycleId,Number(req.user.sub)));}));
router.post('/conteos/:id/cancelar',asyncHandler(async(req,res)=>{if(!req.user.can_authorize_inventory_adjustments)fail('Solo el administrador global puede cancelar conteos.',403);const cycleId=validate(id,req.params.id);await cycleScope(req,cycleId);const body=validate(Joi.object({password:Joi.string().min(1).max(200).required(),motivo:Joi.string().trim().min(1).max(500).required()}),req.body);await verifyPassword(Number(req.user.sub),body.password);res.json(await cancelCycle(cycleId,Number(req.user.sub),body.motivo));}));

router.post('/conteos/evidencias',express.raw({type:['image/jpeg','image/png','image/webp'],limit:'2mb'}),asyncHandler(async(req,res)=>{const branch=validate(id,req.query.sucursal_id);await resolveInventoryScope(req.user,branch,pool);const data=req.body;if(!Buffer.isBuffer(data)||data.length<12)fail('Selecciona una imagen JPEG, PNG o WebP.');let extension;if(data.subarray(0,3).equals(Buffer.from([255,216,255]))&&req.is('image/jpeg'))extension='jpg';if(data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))&&req.is('image/png'))extension='png';if(data.toString('ascii',0,4)==='RIFF'&&data.toString('ascii',8,12)==='WEBP'&&req.is('image/webp'))extension='webp';if(!extension)fail('El contenido no corresponde a una imagen permitida.');await fs.mkdir(directory,{recursive:true});const filename=`${randomUUID()}.${extension}`;await fs.writeFile(path.join(directory,filename),data,{flag:'wx'});res.status(201).json({evidencia_url:`/inventario/conteos/evidencias/${filename}`});}));
router.get('/conteos/evidencias/:filename',asyncHandler(async(req,res,next)=>{if(!filenamePattern.test(req.params.filename))fail('Evidencia no encontrada.',404);const url=`/inventario/conteos/evidencias/${req.params.filename}`;const[rows]=await pool.query('SELECT c.sucursal_id FROM inv_conteo_ciclico_detalle d JOIN inv_conteo_ciclico c ON c.id=d.conteo_id WHERE d.evidencia_url=?',[url]);if(!rows.length)fail('Evidencia no encontrada.',404);await resolveInventoryScope(req.user,rows[0].sucursal_id,pool);res.set('Cache-Control','private, no-store');res.set('X-Content-Type-Options','nosniff');res.sendFile(req.params.filename,{root:directory},error=>{if(error&&!res.headersSent){if(error.code==='ENOENT'||error.status===404)res.status(404).json({message:'Evidencia no encontrada.'});else next(error);}});}));

router.get('/conteos-reporte',asyncHandler(async(req,res)=>{const q=validate(listSchema,req.query);if(q.sucursal_id)await resolveInventoryScope(req.user,q.sucursal_id,pool);const filter=q.sucursal_id?{sql:'c.sucursal_id=?',params:[q.sucursal_id]}:scopeFilter(req.user,'c.sucursal_id');const conditions=[filter.sql,'c.created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? DAY)'],params=[...filter.params,q.dias];const[[summary]]=await pool.query(`SELECT COUNT(DISTINCT c.id) conteos,COUNT(d.id) partidas,SUM(d.cantidad_contada IS NOT NULL) partidas_contadas,SUM(d.diferencia<>0) diferencias,COUNT(DISTINCT CASE WHEN c.estado='COMPLETADO' THEN c.id END) completados FROM inv_conteo_ciclico c JOIN inv_conteo_ciclico_detalle d ON d.conteo_id=c.id WHERE ${conditions.join(' AND ')}`,params);const[items]=await pool.query(`SELECT c.folio,c.semana,c.zona,c.estado,s.nombre sucursal_nombre,a.nombre almacen_nombre,COUNT(d.id) partidas,SUM(d.cantidad_contada IS NOT NULL) contadas,SUM(d.diferencia<>0) diferencias FROM inv_conteo_ciclico c JOIN inv_conteo_ciclico_detalle d ON d.conteo_id=c.id JOIN cat_sucursal s ON s.id=c.sucursal_id JOIN inv_almacen a ON a.id=c.almacen_id WHERE ${conditions.join(' AND ')} GROUP BY c.id,c.folio,c.semana,c.zona,c.estado,s.nombre,a.nombre ORDER BY c.semana DESC LIMIT ? OFFSET ?`,[...params,q.limit,q.offset]);res.json({summary,items,total:Number(summary.conteos||0),dias:q.dias});}));
module.exports=router;
