const router=require('express').Router();
const Joi=require('joi');
const bcrypt=require('bcryptjs');
const {pool}=require('../../config/db');
const asyncHandler=require('../../utils/asyncHandler');
const {resolveInventoryScope,inventoryScope}=require('../../utils/inventoryAccess');
const {saveDraftOrder,transitionOrder,receiveOrder}=require('../../services/inventoryPurchasing');

const id=Joi.number().integer().min(1).max(Number.MAX_SAFE_INTEGER).required();
const decimal=Joi.string().pattern(/^(0|[1-9]\d{0,11})(\.\d{1,6})?$/).required();
const positive=Joi.string().pattern(/^(?!0(?:\.0{1,6})?$)(0|[1-9]\d{0,11})(\.\d{1,6})?$/).required();
const optional=max=>Joi.string().trim().max(max).allow('',null).empty('').default(null);
const providerSchema=Joi.object({razon_social:Joi.string().trim().min(1).max(180).required(),nombre_comercial:Joi.string().trim().min(1).max(180).required(),
  rfc:optional(20),contacto:optional(180),telefono:optional(40),email:Joi.string().email().max(180).allow('',null).empty('').default(null),condiciones_pago:optional(180),
  dias_entrega:Joi.number().integer().min(0).max(3650).default(0),calificacion:Joi.number().min(0).max(5).precision(2).default(0),notas:optional(500),activo:Joi.boolean().default(true),
  sucursal_ids:Joi.array().min(1).items(id).unique().required()});
const orderSchema=Joi.object({sucursal_id:id,almacen_id:id,proveedor_id:id,fecha_estimada:Joi.date().iso().allow(null,'').empty('').default(null),condiciones_pago:optional(180),notas:optional(500),
  detalles:Joi.array().min(1).max(200).items(Joi.object({producto_id:id,cantidad:positive,costo_esperado:decimal})).required()});
const receiveSchema=Joi.object({ubicacion_id:id,factura_proveedor:Joi.string().trim().min(1).max(180).required(),idempotencia:Joi.string().pattern(/^[A-Za-z0-9_.:-]{16,80}$/).required(),
  fecha_recepcion:Joi.date().iso().max('now').optional(),detalles:Joi.array().min(1).max(200).items(Joi.object({orden_detalle_id:id,cantidad:positive,costo_real:decimal})).required()});
const listSchema=Joi.object({sucursal_id:id.optional(),q:Joi.string().trim().max(180).allow('').default(''),estado:Joi.string().valid('BORRADOR','PENDIENTE_AUTORIZACION','AUTORIZADA','ENVIADA','PARCIAL','RECIBIDA','RECHAZADA','CANCELADA').optional(),
  proveedor_id:id.optional(),producto_id:id.optional(),dias:Joi.number().integer().min(1).max(3650).default(90),limit:Joi.number().integer().min(1).max(100).default(50),offset:Joi.number().integer().min(0).max(1000000).default(0)});
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
function validate(schema,value){const result=schema.validate(value,{abortEarly:false,allowUnknown:false});if(result.error)fail('Revisa los campos: '+result.error.details.map(item=>item.path.join('.')).join(', '));return result.value;}
async function password(userId,value){const [rows]=await pool.query('SELECT password_hash FROM usuario WHERE id=? AND activo=1',[userId]);if(!rows.length||!await bcrypt.compare(value,rows[0].password_hash))fail('La contraseña es incorrecta.',403);}
function scopeFilter(user,column='i.sucursal_id'){const ids=inventoryScope(user);if(ids===null)return{sql:'1=1',params:[]};return{sql:`${column}=?`,params:[ids[0]]};}
async function orderScope(req,orderId){const [rows]=await pool.query('SELECT sucursal_id,estado FROM inv_orden_compra WHERE id=?',[orderId]);if(!rows.length)fail('La orden de compra no existe.',404);await resolveInventoryScope(req.user,rows[0].sucursal_id,pool);return rows[0];}

router.get('/proveedores',asyncHandler(async(req,res)=>{const q=validate(listSchema,req.query);const scope=await resolveInventoryScope(req.user,q.sucursal_id,pool);const filter=scope.sucursalIds===null?{sql:'1=1',params:[]}:{sql:`EXISTS(SELECT 1 FROM inv_proveedor_sucursal x WHERE x.proveedor_id=i.id AND x.sucursal_id=?)`,params:[scope.sucursalIds[0]]};
  const conditions=[filter.sql],params=[...filter.params];if(q.q){const search=`%${q.q.replace(/[!%_]/g,v=>`!${v}`)}%`;conditions.push("(i.nombre_comercial LIKE ? ESCAPE '!' OR i.razon_social LIKE ? ESCAPE '!' OR i.rfc LIKE ? ESCAPE '!')");params.push(search,search,search);}if(q.proveedor_id){conditions.push('i.id=?');params.push(q.proveedor_id);}
  const where=conditions.join(' AND ');const [[count]]=await pool.query(`SELECT COUNT(*) total FROM inv_proveedor i WHERE ${where}`,params);const [items]=await pool.query(`SELECT i.*,GROUP_CONCAT(ps.sucursal_id ORDER BY ps.sucursal_id) sucursal_ids FROM inv_proveedor i
    JOIN inv_proveedor_sucursal ps ON ps.proveedor_id=i.id WHERE ${where} GROUP BY i.id ORDER BY i.activo DESC,i.nombre_comercial LIMIT ? OFFSET ?`,[...params,q.limit,q.offset]);
  res.json({items:items.map(row=>({...row,sucursal_ids:String(row.sucursal_ids).split(',').map(Number)})),total:Number(count.total),limit:q.limit,offset:q.offset});}));

async function saveProvider(req,res){if(!req.user.can_manage_inventory_catalog)fail('Solo el administrador global puede modificar proveedores.',403);const body=validate(providerSchema,req.body);const providerId=req.params.id?validate(id,req.params.id):null;const db=await pool.getConnection();try{await db.beginTransaction();
  const [branches]=await db.query(`SELECT id FROM cat_sucursal WHERE id IN (${body.sucursal_ids.map(()=>'?').join(',')}) FOR UPDATE`,body.sucursal_ids);if(branches.length!==body.sucursal_ids.length)fail('Una sucursal seleccionada no existe.');let before=null;let resultId=providerId;
  const fields=[body.razon_social,body.nombre_comercial,body.rfc,body.contacto,body.telefono,body.email,body.condiciones_pago,body.dias_entrega,body.calificacion,body.notas,body.activo?1:0];
  if(providerId){const [rows]=await db.query('SELECT * FROM inv_proveedor WHERE id=? FOR UPDATE',[providerId]);if(!rows.length)fail('El proveedor no existe.',404);before=rows[0];await db.query(`UPDATE inv_proveedor SET razon_social=?,nombre_comercial=?,rfc=?,contacto=?,telefono=?,email=?,condiciones_pago=?,dias_entrega=?,calificacion=?,notas=?,activo=? WHERE id=?`,[...fields,providerId]);
    const [used]=await db.query(`SELECT DISTINCT sucursal_id FROM inv_orden_compra WHERE proveedor_id=? UNION SELECT DISTINCT sucursal_id FROM inv_producto_proveedor WHERE proveedor_id=?`,[providerId,providerId]);const keep=new Set(body.sucursal_ids);if(used.some(row=>!keep.has(Number(row.sucursal_id))))fail('No se puede retirar una sucursal que ya tiene compras o productos asociados.',409);await db.query(`DELETE FROM inv_proveedor_sucursal WHERE proveedor_id=? AND sucursal_id NOT IN (${body.sucursal_ids.map(()=>'?').join(',')})`,[providerId,...body.sucursal_ids]);
  }else{const [created]=await db.query(`INSERT INTO inv_proveedor(razon_social,nombre_comercial,rfc,contacto,telefono,email,condiciones_pago,dias_entrega,calificacion,notas,activo,creado_por) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[...fields,Number(req.user.sub)]);resultId=Number(created.insertId);}
  await db.query('INSERT IGNORE INTO inv_proveedor_sucursal(proveedor_id,sucursal_id) VALUES ?',[body.sucursal_ids.map(branchId=>[resultId,branchId])]);await db.query(`INSERT INTO inv_auditoria(usuario_id,accion,entidad,entidad_id,antes,despues) VALUES (?,?,?,?,?,?)`,[Number(req.user.sub),before?'ACTUALIZAR':'CREAR','inv_proveedor',resultId,before?JSON.stringify(before):null,JSON.stringify(body)]);await db.commit();res.status(providerId?200:201).json({id:resultId,...body});
  }catch(error){await db.rollback();if(error.code==='ER_DUP_ENTRY')fail('Ya existe un proveedor con ese RFC.',409);throw error;}finally{db.release();}}
router.post('/proveedores',asyncHandler(saveProvider));router.put('/proveedores/:id',asyncHandler(saveProvider));

router.get('/proveedores-productos',asyncHandler(async(req,res)=>{const q=validate(listSchema,req.query);const scope=await resolveInventoryScope(req.user,q.sucursal_id,pool);const filter=scope.sucursalIds===null?{sql:'1=1',params:[]}:{sql:'i.sucursal_id=?',params:[scope.sucursalIds[0]]};const [items]=await pool.query(`SELECT i.*,p.sku,p.nombre_comercial,pr.nombre_comercial proveedor_nombre FROM inv_producto_proveedor i JOIN inv_producto p ON p.id=i.producto_id JOIN inv_proveedor pr ON pr.id=i.proveedor_id WHERE ${filter.sql} ORDER BY p.nombre_comercial`,filter.params);res.json({items,total:items.length});}));
router.put('/proveedores/:id/productos/:productoId',asyncHandler(async(req,res)=>{const providerId=validate(id,req.params.id),productId=validate(id,req.params.productoId);const body=validate(Joi.object({sucursal_id:id,sku_proveedor:optional(100),costo_referencia:decimal,preferido:Joi.boolean().default(false)}),req.body);await resolveInventoryScope(req.user,body.sucursal_id,pool);const db=await pool.getConnection();try{await db.beginTransaction();const [valid]=await db.query(`SELECT ps.proveedor_id FROM inv_proveedor_sucursal ps JOIN inv_proveedor p ON p.id=ps.proveedor_id AND p.activo=1 JOIN inv_producto pr ON pr.id=? AND pr.activo=1 WHERE ps.proveedor_id=? AND ps.sucursal_id=? FOR UPDATE`,[productId,providerId,body.sucursal_id]);if(!valid.length)fail('El proveedor o producto no está disponible para la sucursal.');const [before]=await db.query('SELECT * FROM inv_producto_proveedor WHERE producto_id=? AND proveedor_id=? AND sucursal_id=? FOR UPDATE',[productId,providerId,body.sucursal_id]);if(body.preferido)await db.query('UPDATE inv_producto_proveedor SET preferido=0 WHERE producto_id=? AND sucursal_id=?',[productId,body.sucursal_id]);await db.query(`INSERT INTO inv_producto_proveedor(producto_id,proveedor_id,sucursal_id,sku_proveedor,costo_referencia,preferido) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE sku_proveedor=VALUES(sku_proveedor),costo_referencia=VALUES(costo_referencia),preferido=VALUES(preferido)`,[productId,providerId,body.sucursal_id,body.sku_proveedor,body.costo_referencia,body.preferido?1:0]);await db.query(`INSERT INTO inv_auditoria(sucursal_id,usuario_id,accion,entidad,entidad_id,antes,despues) VALUES (?,?,?,?,?,?,?)`,[body.sucursal_id,Number(req.user.sub),before.length?'ACTUALIZAR':'CREAR','inv_producto_proveedor',productId,before.length?JSON.stringify(before[0]):null,JSON.stringify({producto_id:productId,proveedor_id:providerId,...body})]);await db.commit();res.json({producto_id:productId,proveedor_id:providerId,...body});}catch(error){await db.rollback();throw error;}finally{db.release();}}));

router.get('/compras/propuestas',asyncHandler(async(req,res)=>{const q=validate(listSchema,req.query);const scope=await resolveInventoryScope(req.user,q.sucursal_id,pool);const filter=scope.sucursalIds===null?{sql:'1=1',params:[]}:{sql:'pa.sucursal_id=?',params:[scope.sucursalIds[0]]};const conditions=[filter.sql,'pa.punto_reorden>0'],params=[...filter.params];if(q.q){const search=`%${q.q.replace(/[!%_]/g,v=>`!${v}`)}%`;conditions.push("(p.sku LIKE ? ESCAPE '!' OR p.nombre_comercial LIKE ? ESCAPE '!')");params.push(search,search);}const [items]=await pool.query(`SELECT pa.producto_id,pa.almacen_id,pa.sucursal_id,p.sku,p.nombre_comercial,a.nombre almacen_nombre,s.nombre sucursal_nombre,pa.punto_reorden,pa.maximo,
    COALESCE(SUM(e.cantidad),0) cantidad,GREATEST(pa.maximo-COALESCE(SUM(e.cantidad),0),0) cantidad_sugerida,pp.proveedor_id,pr.nombre_comercial proveedor_nombre,COALESCE(pp.costo_referencia,c.costo_promedio,0) costo_referencia
    FROM inv_producto_almacen pa JOIN inv_producto p ON p.id=pa.producto_id AND p.activo=1 JOIN inv_almacen a ON a.id=pa.almacen_id AND a.activo=1 JOIN cat_sucursal s ON s.id=pa.sucursal_id
    LEFT JOIN inv_existencia e ON e.producto_id=pa.producto_id AND e.almacen_id=pa.almacen_id LEFT JOIN inv_producto_proveedor pp ON pp.producto_id=pa.producto_id AND pp.sucursal_id=pa.sucursal_id AND pp.preferido=1
    LEFT JOIN inv_proveedor pr ON pr.id=pp.proveedor_id LEFT JOIN inv_costo_sucursal c ON c.producto_id=pa.producto_id AND c.sucursal_id=pa.sucursal_id WHERE ${conditions.join(' AND ')}
    GROUP BY pa.producto_id,pa.almacen_id,pa.sucursal_id,p.sku,p.nombre_comercial,a.nombre,s.nombre,pa.punto_reorden,pa.maximo,pp.proveedor_id,pr.nombre_comercial,pp.costo_referencia,c.costo_promedio
    HAVING cantidad<=pa.punto_reorden ORDER BY (cantidad=0) DESC,p.nombre_comercial LIMIT ? OFFSET ?`,[...params,q.limit,q.offset]);res.json({items,total:items.length,limit:q.limit,offset:q.offset});}));

router.get('/compras/ordenes',asyncHandler(async(req,res)=>{const q=validate(listSchema,req.query);const scope=await resolveInventoryScope(req.user,q.sucursal_id,pool);const filter=scope.sucursalIds===null?{sql:'1=1',params:[]}:{sql:'i.sucursal_id=?',params:[scope.sucursalIds[0]]};const conditions=[filter.sql],params=[...filter.params];if(q.estado){conditions.push('i.estado=?');params.push(q.estado);}if(q.proveedor_id){conditions.push('i.proveedor_id=?');params.push(q.proveedor_id);}if(q.q){const search=`%${q.q.replace(/[!%_]/g,v=>`!${v}`)}%`;conditions.push("(i.folio LIKE ? ESCAPE '!' OR p.nombre_comercial LIKE ? ESCAPE '!')");params.push(search,search);}const where=conditions.join(' AND ');const [[count]]=await pool.query(`SELECT COUNT(*) total FROM inv_orden_compra i JOIN inv_proveedor p ON p.id=i.proveedor_id WHERE ${where}`,params);const [items]=await pool.query(`SELECT i.*,p.nombre_comercial proveedor_nombre,s.nombre sucursal_nombre,a.nombre almacen_nombre,u.nombre creado_por_nombre FROM inv_orden_compra i JOIN inv_proveedor p ON p.id=i.proveedor_id JOIN cat_sucursal s ON s.id=i.sucursal_id JOIN inv_almacen a ON a.id=i.almacen_id JOIN usuario u ON u.id=i.creado_por WHERE ${where} ORDER BY i.created_at DESC LIMIT ? OFFSET ?`,[...params,q.limit,q.offset]);if(items.length){const [details]=await pool.query(`SELECT d.*,p.sku,p.nombre_comercial FROM inv_orden_compra_detalle d JOIN inv_producto p ON p.id=d.producto_id WHERE d.orden_compra_id IN (${items.map(()=>'?').join(',')}) ORDER BY d.id`,items.map(row=>row.id));for(const item of items)item.detalles=details.filter(line=>Number(line.orden_compra_id)===Number(item.id));}res.json({items,total:Number(count.total),limit:q.limit,offset:q.offset});}));
router.post('/compras/ordenes',asyncHandler(async(req,res)=>{const body=validate(orderSchema,req.body);await resolveInventoryScope(req.user,body.sucursal_id,pool);res.status(201).json(await saveDraftOrder(body,Number(req.user.sub)));}));
router.put('/compras/ordenes/:id',asyncHandler(async(req,res)=>{const orderId=validate(id,req.params.id);const body=validate(orderSchema,req.body);await orderScope(req,orderId);await resolveInventoryScope(req.user,body.sucursal_id,pool);res.json(await saveDraftOrder(body,Number(req.user.sub),orderId));}));
router.post('/compras/ordenes/:id/acciones/:action',asyncHandler(async(req,res)=>{const orderId=validate(id,req.params.id);const action=validate(Joi.string().valid('solicitar','autorizar','enviar','rechazar','cancelar').required(),req.params.action);await orderScope(req,orderId);const sensitive=['autorizar','rechazar','cancelar'].includes(action);if(sensitive&&!req.user.can_authorize_inventory_adjustments)fail('Solo el administrador global puede autorizar, rechazar o cancelar compras.',403);const body=validate(sensitive?Joi.object({password:Joi.string().min(1).max(200).required(),motivo:Joi.string().trim().min(1).max(500).required()}):Joi.object({}),req.body||{});if(sensitive)await password(Number(req.user.sub),body.password);res.json(await transitionOrder(orderId,action,Number(req.user.sub),body.motivo));}));
router.post('/compras/ordenes/:id/recepciones',asyncHandler(async(req,res)=>{const orderId=validate(id,req.params.id);await orderScope(req,orderId);const body=validate(receiveSchema,req.body);const result=await receiveOrder(orderId,body,Number(req.user.sub));res.status(result.duplicated?200:201).json(result);}));

router.get('/compras/reporte',asyncHandler(async(req,res)=>{const q=validate(listSchema,req.query);const scope=await resolveInventoryScope(req.user,q.sucursal_id,pool);const filter=scope.sucursalIds===null?{sql:'1=1',params:[]}:{sql:'r.sucursal_id=?',params:[scope.sucursalIds[0]]};const conditions=[filter.sql,'r.fecha_recepcion>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? DAY)'],params=[...filter.params,q.dias];if(q.proveedor_id){conditions.push('o.proveedor_id=?');params.push(q.proveedor_id);}if(q.producto_id){conditions.push('d.producto_id=?');params.push(q.producto_id);}const where=conditions.join(' AND ');const [[summary]]=await pool.query(`SELECT COUNT(DISTINCT r.id) recepciones,COALESCE(SUM(d.importe_real),0) total_comprado,COALESCE(SUM(d.cantidad*d.variacion_unitaria),0) variacion_total FROM inv_recepcion_compra r JOIN inv_orden_compra o ON o.id=r.orden_compra_id JOIN inv_recepcion_compra_detalle d ON d.recepcion_id=r.id WHERE ${where}`,params);const [items]=await pool.query(`SELECT r.id,r.folio,r.factura_proveedor,r.fecha_recepcion,o.folio orden_folio,p.nombre_comercial proveedor_nombre,s.nombre sucursal_nombre,SUM(d.importe_real) total_real,SUM(d.cantidad*d.costo_esperado) total_esperado,SUM(d.cantidad*d.variacion_unitaria) variacion_total FROM inv_recepcion_compra r JOIN inv_orden_compra o ON o.id=r.orden_compra_id JOIN inv_proveedor p ON p.id=o.proveedor_id JOIN cat_sucursal s ON s.id=r.sucursal_id JOIN inv_recepcion_compra_detalle d ON d.recepcion_id=r.id WHERE ${where} GROUP BY r.id,r.folio,r.factura_proveedor,r.fecha_recepcion,o.folio,p.nombre_comercial,s.nombre ORDER BY r.fecha_recepcion DESC LIMIT ? OFFSET ?`,[...params,q.limit,q.offset]);res.json({summary,items,total:Number(summary.recepciones),dias:q.dias});}));

module.exports=router;
