const crypto=require('node:crypto');
const {pool}=require('../config/db');
const {toUnits}=require('./inventoryMovement');
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
const folio=()=>`CC-${new Date().toISOString().replace(/\D/g,'').slice(0,14)}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;

async function createCycle(input,userId){const db=await pool.getConnection();try{await db.beginTransaction();const [warehouse]=await db.query('SELECT id FROM inv_almacen WHERE id=? AND sucursal_id=? AND activo=1 FOR UPDATE',[input.almacen_id,input.sucursal_id]);if(!warehouse.length)fail('El almacén no pertenece a la sucursal o está inactivo.');
  const zone=input.zona.toUpperCase();const [candidates]=await db.query(`SELECT e.producto_id,e.ubicacion_id,e.almacen_id,e.sucursal_id,e.cantidad,p.sku,p.nombre_comercial,u.codigo,
    (SELECT MAX(cd.contado_at) FROM inv_conteo_ciclico_detalle cd WHERE cd.producto_id=e.producto_id AND cd.ubicacion_id=e.ubicacion_id) ultimo_conteo
    FROM inv_existencia e JOIN inv_producto p ON p.id=e.producto_id AND p.activo=1 JOIN inv_ubicacion u ON u.id=e.ubicacion_id AND u.activo=1
    WHERE e.almacen_id=? AND e.sucursal_id=? AND (?='TODAS' OR u.codigo LIKE CONCAT(?,'%'))
    ORDER BY ultimo_conteo IS NULL DESC,ultimo_conteo ASC,e.ultimo_movimiento_at DESC,p.nombre_comercial LIMIT ? FOR UPDATE`,[input.almacen_id,input.sucursal_id,zone,zone,input.cantidad_productos]);if(!candidates.length)fail('No hay existencias configuradas para la zona seleccionada.');
  const cycleFolio=folio();const [created]=await db.query(`INSERT INTO inv_conteo_ciclico(folio,sucursal_id,almacen_id,semana,zona,asignado_a,creado_por) VALUES (?,?,?,?,?,?,?)`,[cycleFolio,input.sucursal_id,input.almacen_id,input.semana,zone,input.asignado_a||null,userId]);
  await db.query(`INSERT INTO inv_conteo_ciclico_detalle(conteo_id,producto_id,ubicacion_id,almacen_id,sucursal_id,existencia_sistema) VALUES ?`,[candidates.map(row=>[created.insertId,row.producto_id,row.ubicacion_id,row.almacen_id,row.sucursal_id,row.cantidad])]);
  await db.query(`INSERT INTO inv_auditoria(sucursal_id,usuario_id,accion,entidad,entidad_id,despues) VALUES (?,?,'CREAR','inv_conteo_ciclico',?,?)`,[input.sucursal_id,userId,created.insertId,JSON.stringify({folio:cycleFolio,semana:input.semana,zona:zone,partidas:candidates.length})]);await db.commit();return{id:Number(created.insertId),folio:cycleFolio,estado:'PROGRAMADO',partidas:candidates.length};
}catch(error){await db.rollback();if(error.code==='ER_DUP_ENTRY')fail('Ya existe un conteo para ese almacén, semana y zona.',409);throw error;}finally{db.release();}}

async function startCycle(cycleId,userId){const db=await pool.getConnection();try{await db.beginTransaction();const [rows]=await db.query('SELECT * FROM inv_conteo_ciclico WHERE id=? FOR UPDATE',[cycleId]);if(!rows.length)fail('El conteo no existe.',404);if(rows[0].estado==='EN_PROCESO'){await db.commit();return{id:Number(cycleId),estado:'EN_PROCESO'};}if(rows[0].estado!=='PROGRAMADO')fail('El conteo no puede iniciarse en su estado actual.',409);await db.query("UPDATE inv_conteo_ciclico SET estado='EN_PROCESO',iniciado_at=UTC_TIMESTAMP(6),asignado_a=COALESCE(asignado_a,?) WHERE id=?",[userId,cycleId]);await db.commit();return{id:Number(cycleId),estado:'EN_PROCESO'};}catch(error){await db.rollback();throw error;}finally{db.release();}}

async function captureCount(cycleId,detailId,input,userId){const db=await pool.getConnection();try{await db.beginTransaction();const [cycles]=await db.query('SELECT * FROM inv_conteo_ciclico WHERE id=? FOR UPDATE',[cycleId]);if(!cycles.length)fail('El conteo no existe.',404);const cycle=cycles[0];if(!['PROGRAMADO','EN_PROCESO'].includes(cycle.estado))fail('El conteo ya no admite capturas.',409);const [details]=await db.query('SELECT * FROM inv_conteo_ciclico_detalle WHERE id=? AND conteo_id=? FOR UPDATE',[detailId,cycleId]);if(!details.length)fail('La partida no pertenece al conteo.',404);if(cycle.estado==='PROGRAMADO')await db.query("UPDATE inv_conteo_ciclico SET estado='EN_PROCESO',iniciado_at=UTC_TIMESTAMP(6),asignado_a=COALESCE(asignado_a,?) WHERE id=?",[userId,cycleId]);await db.query(`UPDATE inv_conteo_ciclico_detalle SET cantidad_contada=?,estado='CONTADO',evidencia_url=?,notas=?,contado_por=?,contado_at=UTC_TIMESTAMP(6) WHERE id=?`,[input.cantidad_contada,input.evidencia_url||null,input.notas||null,userId,detailId]);await db.commit();return{id:Number(detailId),estado:'CONTADO'};}catch(error){await db.rollback();throw error;}finally{db.release();}}

async function completeCycle(cycleId,userId){const db=await pool.getConnection();try{await db.beginTransaction();const [cycles]=await db.query('SELECT * FROM inv_conteo_ciclico WHERE id=? FOR UPDATE',[cycleId]);if(!cycles.length)fail('El conteo no existe.',404);const cycle=cycles[0];if(cycle.estado!=='EN_PROCESO')fail('El conteo debe estar en proceso para completarse.',409);const [details]=await db.query('SELECT * FROM inv_conteo_ciclico_detalle WHERE conteo_id=? ORDER BY id FOR UPDATE',[cycleId]);if(details.some(row=>row.cantidad_contada===null))fail('Todas las partidas deben capturarse antes de completar el conteo.',409);let adjustments=0;
  for(const detail of details){const [stocks]=await db.query('SELECT cantidad FROM inv_existencia WHERE producto_id=? AND ubicacion_id=? AND almacen_id=? AND sucursal_id=? FOR UPDATE',[detail.producto_id,detail.ubicacion_id,detail.almacen_id,detail.sucursal_id]);const current=stocks[0]?.cantidad||'0.000000';if(toUnits(current)!==toUnits(detail.existencia_sistema))fail('La existencia cambió durante el conteo. Programa un conteo nuevo para conservar la trazabilidad.',409);if(toUnits(detail.cantidad_contada)===toUnits(detail.existencia_sistema)){await db.query("UPDATE inv_conteo_ciclico_detalle SET estado='SIN_DIFERENCIA' WHERE id=?",[detail.id]);continue;}const [costs]=await db.query('SELECT costo_promedio FROM inv_costo_sucursal WHERE producto_id=? AND sucursal_id=?',[detail.producto_id,detail.sucursal_id]);const cost=costs[0]?.costo_promedio||'0.000000';const [adjustment]=await db.query(`INSERT INTO inv_ajuste_solicitud(sucursal_id,producto_id,almacen_id,ubicacion_id,existencia_sistema,cantidad_contada,costo_unitario,motivo,solicitado_por) VALUES (?,?,?,?,?,?,?,?,?)`,[detail.sucursal_id,detail.producto_id,detail.almacen_id,detail.ubicacion_id,detail.existencia_sistema,detail.cantidad_contada,cost,`Conteo cíclico ${cycle.folio}, zona ${cycle.zona}`,userId]);await db.query("UPDATE inv_conteo_ciclico_detalle SET estado='AJUSTE_PENDIENTE',ajuste_solicitud_id=? WHERE id=?",[adjustment.insertId,detail.id]);adjustments+=1;}
  await db.query("UPDATE inv_conteo_ciclico SET estado='COMPLETADO',completado_at=UTC_TIMESTAMP(6) WHERE id=?",[cycleId]);await db.query(`INSERT INTO inv_auditoria(sucursal_id,usuario_id,accion,entidad,entidad_id,despues) VALUES (?,?,'COMPLETAR','inv_conteo_ciclico',?,?)`,[cycle.sucursal_id,userId,cycleId,JSON.stringify({partidas:details.length,ajustes:adjustments})]);await db.commit();return{id:Number(cycleId),estado:'COMPLETADO',partidas:details.length,ajustes_pendientes:adjustments};
}catch(error){await db.rollback();throw error;}finally{db.release();}}

async function cancelCycle(cycleId,userId,reason){const db=await pool.getConnection();try{await db.beginTransaction();const [rows]=await db.query('SELECT * FROM inv_conteo_ciclico WHERE id=? FOR UPDATE',[cycleId]);if(!rows.length)fail('El conteo no existe.',404);if(!['PROGRAMADO','EN_PROCESO'].includes(rows[0].estado))fail('El conteo ya no puede cancelarse.',409);await db.query("UPDATE inv_conteo_ciclico SET estado='CANCELADO',cancelado_at=UTC_TIMESTAMP(6) WHERE id=?",[cycleId]);await db.query(`INSERT INTO inv_auditoria(sucursal_id,usuario_id,accion,entidad,entidad_id,antes,despues) VALUES (?,?,'CANCELAR','inv_conteo_ciclico',?,?,?)`,[rows[0].sucursal_id,userId,cycleId,JSON.stringify({estado:rows[0].estado}),JSON.stringify({estado:'CANCELADO',motivo:reason})]);await db.commit();return{id:Number(cycleId),estado:'CANCELADO'};}catch(error){await db.rollback();throw error;}finally{db.release();}}
module.exports={createCycle,startCycle,captureCount,completeCycle,cancelCycle};
