const ROLE_IDS = {
  ADMINISTRADOR: 1,
  AGENTE_EL_SALTO: 2,
  AGENTE_CHAPALA: 3,
  ADMIN_ALAMEDA: 4,
  ADMIN_CHAPALA: 5,
};

const BRANCH_ADMIN_AGENT_ROLES = {
  [ROLE_IDS.ADMIN_ALAMEDA]: ROLE_IDS.AGENTE_EL_SALTO,
  [ROLE_IDS.ADMIN_CHAPALA]: ROLE_IDS.AGENTE_CHAPALA,
};

module.exports = { ROLE_IDS, BRANCH_ADMIN_AGENT_ROLES };
